import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'
import './globals.css'

const koulen = Koulen({ subsets: ['khmer'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={koulen.className}>{children}</body>
    </html>
  )
}
